import { getServerSession } from 'next-auth'; import { authOptions } from '@/lib/auth/auth-options'; import { redirect } from 'next/navigation'; import prisma from '@/lib/utils/prisma'; import { Card, CardContent } from '@/components/ui/card'; import { Badge } from '@/components/ui/badge'; import { Button } from '@/components/ui/button'; import { GraduationCap, Clock, Star, Target, Award, ArrowRight, Play } from 'lucide-react'; import Link from 'next/link';
export default async function StudentExamsPage() {
  let session; try { session = await getServerSession(authOptions); } catch { redirect('/auth/login'); } if (!session?.user) redirect('/auth/login'); if (session.user.role !== 'STUDENT') redirect(`/${session.user.role.toLowerCase()}/dashboard`);
  const student = await prisma.student.findFirst({ where: { userId: session.user.id }, select: { id: true } }); if (!student) return <div className="p-6"><p>Student profile not found.</p></div>;
  const quizzes = await prisma.quiz.findMany({ where: { module: { course: { enrollments: { some: { studentId: student.id } } } } }, include: { module: { include: { course: { select: { title: true, subject: true } } } }, _count: { select: { questions: true } } }, take: 20 });
  const examAttempts = await prisma.examAttempt.findMany({ where: { studentId: student.id }, include: { quiz: { include: { module: { include: { course: { select: { title: true } } } } } } }, orderBy: { completedAt: 'desc' }, take: 5 });
  return (<div className="p-6 space-y-6"><div className="flex items-center gap-3"><div className="p-2.5 bg-red-100 rounded-xl"><GraduationCap size={22} className="text-red" /></div><div><h1 className="text-2xl font-bold text-navy">Mock Exams</h1><p className="text-sm text-grey-medium">Test your knowledge</p></div></div>
  <div className="grid grid-cols-4 gap-3">{[{ l:'Available', v:quizzes.length, i:<Target size={16} className="text-blue-600" />, b:'bg-blue-50' },{ l:'Completed', v:examAttempts.filter(a=>a.completedAt).length, i:<Award size={16} className="text-green" />, b:'bg-green-50' },{ l:'Passed', v:examAttempts.filter(a=>a.passed).length, i:<Star size={16} className="text-yellow-600" />, b:'bg-yellow-50' },{ l:'Avg Score', v:examAttempts.length>0?Math.round(examAttempts.reduce((s,a)=>s+a.score,0)/examAttempts.length)+'%':'N/A', i:<Target size={16} className="text-red" />, b:'bg-red-50' }].map((s,i)=>(<Card key={i} className="border-0 shadow-sm"><CardContent className="p-3 text-center"><div className={`p-1.5 rounded-lg ${s.b} inline-block mb-1`}>{s.i}</div><p className="text-xl font-bold text-navy">{s.v}</p><p className="text-xs text-grey-medium">{s.l}</p></CardContent></Card>))}</div>
  <div><h2 className="text-base font-bold text-navy mb-3">Available Exams</h2><div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">{quizzes.length>0?quizzes.map((quiz)=>(<Link key={quiz.id} href={`/student/exams/${quiz.id}`}><Card className="border-0 shadow-sm hover:shadow-md transition-all group cursor-pointer h-full"><CardContent className="p-5"><Badge variant="info" size="sm" className="mb-2">{quiz.module.course.subject}</Badge><h3 className="font-semibold text-navy mb-1 group-hover:text-red">{quiz.title}</h3><p className="text-xs text-grey-dark mb-3">{quiz.module.course.title}</p><div className="flex items-center gap-3 text-xs text-grey-medium mb-3"><Clock size={12} />{quiz.timeLimit||30}min • {quiz._count.questions}Q • Pass:{quiz.passingScore}%</div><Button variant="primary" size="sm" fullWidth rightIcon={<Play size={14} />}>Start Exam</Button></CardContent></Card></Link>)):<Card className="border-0 shadow-sm col-span-full"><CardContent className="p-8 text-center"><GraduationCap size={40} className="mx-auto text-grey-medium mb-3" /><p className="text-sm text-grey-dark">Enroll in courses to unlock exams.</p></CardContent></Card>}</div></div>
  {examAttempts.length>0&&<div><h2 className="text-base font-bold text-navy mb-3">Recent Attempts</h2><div className="space-y-2">{examAttempts.slice(0,5).map((a)=>(<Card key={a.id} className="border-0 shadow-sm"><CardContent className="p-4 flex items-center justify-between"><div><p className="font-medium text-navy text-sm">{a.quiz?.title||'Unknown'}</p><p className="text-xs text-grey-medium">{a.quiz?.module?.course?.title}</p></div><div className="text-right"><p className={`font-bold ${a.passed?'text-green':'text-red'}`}>{a.score}%</p><Badge variant={a.passed?'success':'error'} size="sm">{a.passed?'Pass':'Fail'}</Badge></div></CardContent></Card>))}</div></div>}
  </div>);}
