export const DEFAULT_CERTIFICATE_TEMPLATE = {
  name: 'StudyHub Default Certificate',
  description: 'Official StudyHub Malawi certificate template with professional design',
  isDefault: true,
  isActive: true,
  designConfig: {
    layout: 'landscape',
    borderStyle: 'double',
    borderWidth: 20,
    borderColor: '#1a1a2e',
    innerBorderColor: '#e94560',
    headerText: 'Certificate of Achievement',
    subheaderText: 'This is to certify that',
    footerText: 'Verify at: {{verificationUrl}}',
    showLogo: true,
    showSeal: true,
    showSignature: true,
    signatureLines: 2,
    primaryFont: 'Georgia, serif',
    secondaryFont: 'Arial, sans-serif',
    titleFontSize: 48,
    subtitleFontSize: 18,
    recipientFontSize: 36,
    descriptionFontSize: 16,
    courseTitleFontSize: 24,
    spacing: {
      headerMargin: 30,
      contentMargin: 40,
      footerMargin: 40,
    },
  },
};
